export const Login = () => import("@/views/Login/login.vue")
export const Analysis = () => import("@/views/Dashboard/analysis.vue")
export const Workplace = () => import("@/views/Dashboard/workplace.vue")
export const Pdf = () => import("@/views/Document/pdf.vue")
export const AgGrid = () => import("@/views/Table/AgGrid.vue")